### ISSUE TITLE
NullPointerException in GenericAdPlugin.java:187

### ISSUE THREAD

**Issue by kirmandi** [floatinghotpot/cordova-extension#1]
(as the exception directly affect this extension i post the issue here)

got a user that provided me with this extract of LogCat on an Android 4.4 device
my app uses the AdMob Plugin on cordova 3.7.0

```
Uncaught exception from plugin
                        E  java.lang.NullPointerException
                        E      at com.rjfun.cordova.ad.GenericAdPlugin.execute(GenericAdPlugin.java:187)
                        E      at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:84)
                        E      at org.apache.cordova.PluginManager.exec(PluginManager.java:147)
                        E      at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
                        E      at org.apache.cordova.ExposedJsApi.exec(ExposedJsApi.java:40)
                        E      at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                        E      at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:24)
                        E      at android.os.Handler.dispatchMessage(Handler.java:102)
                        E      at android.os.Looper.loop(Looper.java:136)
                        E      at android.os.HandlerThread.run(HandlerThread.java:61)
                        E  Uncaught exception from plugin
                        E  java.lang.NullPointerException
                        E      at com.rjfun.cordova.ad.GenericAdPlugin.execute(GenericAdPlugin.java:187)
                        E      at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:84)
                        E      at org.apache.cordova.PluginManager.exec(PluginManager.java:147)
                        E      at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
                        E      at org.apache.cordova.ExposedJsApi.exec(ExposedJsApi.java:40)
                        E      at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                        E      at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:24)
                        E      at android.os.Handler.dispatchMessage(Handler.java:102)
                        E      at android.os.Looper.loop(Looper.java:136)
                        E      at android.os.HandlerThread.run(HandlerThread.java:61)
```

no particular case to reproduce, but would be nice if the affected variable could at least be checked against null or put inside a try catch environment so that it does not crash

**Comment by floatinghotpot** [comment]
Thanks for the bug report. Here is the source code:
```java
        } else if (ACTION_PREPARE_INTERSTITIAL.equals(action)) {
            JSONObject options = inputs.optJSONObject(0);
            if(options.length() > 1) { // <----- line 187
            	this.setOptions(options);
            }
```
Unless no args or bad args passed to prepareInterstitial(...), correct javascript call should be:
```javascript
        AdPlugin.prepareInterstitial({adId:admobid.interstitial, autoShow:autoshow});
```

Which ad plugin are you using?

**Comment by kirmandi** [comment]
thanks for getting back so fast and providing inside into the source code
i am using the AdMob Pro Plugin.

seems i was mistaken about the usage of the setOptions() method, as i assumed that if i provide the necessary settings here, that i can ommit the options attribute to any other calls.
the interesting thing here is, that i never encountered this exception on any of my test devices with fully working ads and no problems at all.

as a suggestion check that there is in fact an options attribute before calling the length of a possible null object or clearly state in all documentations that the options attribute is required to be at least an empty object and not optional.
