### ISSUE TITLE
Error happened during install

### ISSUE THREAD

**Issue by balicekt** [floatinghotpot/cordova-extension#7]
Hello, after update last night I tried to install this plugin. But I got this error: 

Fetching plugin "https://github.com/floatinghotpot/cordova-extension" via git clone
Repository "https://github.com/floatinghotpot/cordova-extension" checked out to git ref "master".
Saving plugin to package.json file

Error happened [TypeError: Object.keys called on non-object]
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at Object.getPluginFromFetchJsonByLocator (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:735:26)
    at Object.savePlugin (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:671:36)
    at /usr/local/lib/node_modules/ionic/lib/ionic/cordova.js:90:22
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)

**Comment by floatinghotpot** [comment]
please upgrade your cordova CLI to 5.x, then run:
```bash
cordova plugin add cordova-plugin-extension
```

BTW, this plugin is used as dependency of other plugins like "cordova-plugin-admobpro" and will be installed automatically when install them.

**Comment by balicekt** [comment]
yes "cordova plugin add" is working properly. But I have problem with npm when I use ionic plugin add cordova-plugin-extension

**Comment by zwacky** [comment]
ran into the same problem but with an entirely *different* plugin.

when using `ionic plugin add GITURL`, but `cordova plugin add GITURL` works.
